[project]
name = "semantic-layer-skipping"
version = "0.1.0"
description = "Implementation of layer skipping in LLMs based on semantic caching."
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "transformer-lens>=2.16.1",
]
